stages:
  - deploy

deploy_html:
  stage: deploy
  script:
    - echo "Built Html:"
    - pwd
    - cp ros2.repos ~/qiuzhanpeng/cross
    - cd ~/qiuzhanpeng/cross
    #输入密码到sudo当中，后续便不需要继续执行此命令了
    - echo "sss" | sudo -S bash enterCross_auto.sh 
    - echo "all done!"
  timeout: 4h