stages:
  - deploy

deploy_html:
  stage: deploy
  script:
    - echo "Built Html:"
    - pwd
    - cp ros2.repos ~/qiuzhanpeng/cross
    - cd ~/qiuzhanpeng/cross
    - echo "sss" | sudo -S bash enterCross.sh 
