stages:
  - deploy

deploy_html:
  stage: deploy
  script:
    - echo "Built Html:"
    - pwd
    - cp ros2.repos ~/qiuzhanpeng/cross
    - cd ~/qiuzhanpeng/cross
    - sudo -S cat ~/qiuzhanpeng/password 
    - sudo bash enterCross.sh
