stages:
  - deploy

deploy_html:
  stage: deploy
  script:
    - echo "Built Html:"
    - pwd
    - cp ros2.repos ~/qiuzhanpeng/cross
    - cd ~/qiuzhanpeng/cross
    #输入密码到sudo当中，后续便不需要继续执行此命令了
    - echo "sss" | sudo -S bash enterCross_auto.sh 
    - echo "done!"
    #复制docker文件夹的内容到public做准备
    - docker cp cb8b3be9f4ef:/opt/nros-$(date +%Y%m).tar.gz /public/ReleaseMiddleWare
    - docker cp cb8b3be9f4ef:/opt/ros3rd-$(date +%Y%m).tar.gz /public/ReleaseMiddleWare
  timeout: 12h