
name: Docker Image CI

on:
  push:
    branches: [ "humble-2309" ]
  pull_request:
    branches: [ "humble-2309" ]
jobs:
  build:
    runs-on: [self-hosted, linux,x86]
    steps:
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }} 
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -f Dockerfile.humble -t nros:0.9 .
    - name: Docker image push
      run: docker push nros:0.9
