name: Docker Image CI
on:
  push:
    branches: [ "humble_2309" ]
  pull_request:
    branches: [ "humble_2309" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }} 
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -f Dockerfile.humble -t ${{ secrets.DOCKERHUB_USERNAME }}/ros2code:humble .
    - name: Docker image push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ros2code:humble
